catalog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('twitch/', views.twitch, name='twitch'),
    path('links/', views.LinkView.as_view(), name='links'),
    path('map_link/<int:pk>', views.LinkDetailView.as_view(), name='link-detail'),
    path('maps/', views.MapView.as_view(), name='maps'),
    path('map/<int:pk>', views.MapDetailView.as_view(), name='map-detail'),
    path('videos/', views.VideoView.as_view(), name='videos'),
    path('videos/<int:pk>', views.VideoDetailView.as_view(), name='videos-detail'),
    path('search/', views.SearchResultsView.as_view(), name='search_results'),
    path('videos/create/', views.VideoCreate.as_view(), name='video-create'),
    path('videos/<int:pk>/add_favorite_video/',
         views.add_favorite_video, name='add-favorite-video'),
    path('videos/<int:pk>/remove_favorite_video/',
         views.remove_favorite_video, name='remove-favorite-video'),
]

cstube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='catalog/')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.db import models
# Used to generate URLs by reversing the URL patterns
from django.urls import reverse


class Maps(models.Model):
    """Model representing map."""
    name = models.CharField(
        max_length=200, help_text='Enter a map (e.g. Inferno)')

    def __str__(self):
        """String for representing the Model object."""
        return self.name

    class Meta:
        verbose_name = "Map"


class Videos(models.Model):
    title = models.CharField(max_length=40)
    created_at = models.DateTimeField(auto_now_add=True)
    link = models.URLField(
        max_length=300,
        # help_text='Enter the link'
    )
    map_belong = models.ForeignKey(
        Maps, on_delete=models.SET_NULL, null=True)
    SITE = (
        ('a', 'A'),
        ('b', 'B'),
        ('mid', 'Middle'),
    )
    TYPE = (
        ('Smoke', 'smoke'),
        ('Molly', 'molly'),
        ('Flash', 'flash'),
        ('Nade', 'grenade'),
        ('Strat', 'strat'),
        ('Misc', 'misc'),
    )
    type_video = models.CharField(
        max_length=6,
        choices=TYPE,
        blank=True,
        # help_text='Pick a type',
    )
    site = models.CharField(
        max_length=3,
        choices=SITE,
        blank=True,
        default='a',
        # help_text='Site availability',
    )
    admin_permission = models.BooleanField(default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """Returns the url to access a detail record for this video."""
        return reverse('videos')

    def youtube_id(self):
        link = self.link.split('/')[-1]
        link_arr = link.split('?')
        youtube_id = link_arr[0] + '?star' + link_arr[1]
        return youtube_id

    class Meta:
        verbose_name = 'Video'


class Links(models.Model):
    title = models.CharField(max_length=40)
    created_at = models.DateTimeField(auto_now_add=True)
    link = models.URLField(
        max_length=300,
        # help_text='Enter the link'
    )
    map_belong = models.ForeignKey(
        Maps, on_delete=models.SET_NULL, null=True)
    SITE = (
        ('a', 'A'),
        ('b', 'B'),
        ('mid', 'Middle'),
    )
    TYPE = (
        ('Smoke', 'smoke'),
        ('Molly', 'molly'),
        ('Flash', 'flash'),
        ('Nade', 'grenade'),
    )
    type_video = models.CharField(
        max_length=6,
        choices=TYPE,
        blank=True,
        # help_text='Pick a type',
    )
    site = models.CharField(
        max_length=3,
        choices=SITE,
        blank=True,
        default='a',
        # help_text='Site availability',
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        """Returns the url to access a detail record for this video."""
        return reverse('links')

    class Meta:
        verbose_name = 'Link'

catalog/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.views.generic.edit import CreateView
from django.contrib.postgres.search import SearchVector
from django.http import HttpResponseRedirect

from catalog.models import Maps, Videos, Links

import requests
import environ
from pathlib import Path


def index(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_maps = Maps.objects.all().count()
    num_videos = Videos.objects.filter(admin_permission=True).count()

    # with urllib.request.urlopen("https://www.reddit.com/r/GlobalOffensive/top.json?t=week") as url:
    #     data = json.loads(url.read().decode())

    # reddit_data = data['data']['children'][:10]
    context = {
        'num_maps': num_maps,
        'num_videos': num_videos,
        # 'reddit_data': reddit_data
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)


class MapView(generic.ListView):
    model = Maps


class MapDetailView(generic.DetailView):
    model = Maps


class LinkView(generic.ListView):
    model = Links

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the maps
        context['map_link_list'] = Maps.objects.all()
        return context


class LinkDetailView(generic.DetailView):
    model = Links

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the maps
        context['collections'] = Maps.objects.all()
        context['map_link_list_detail'] = get_object_or_404(
            Maps, pk=self.kwargs['pk'])
        return context


class VideoView(generic.ListView):
    model = Videos

    queryset = Videos.objects.filter(admin_permission=True)

    # def filter_map(self, map_name):
    #     return Videos.objects.filter(map_belong__icontains=map_name)


class VideoDetailView(generic.DetailView):
    model = Videos


def add_favorite_video(request, pk):
    if request.method == 'POST':
        favorite = Videos.objects.get(pk=pk)
        user = request.user
        user.favorite_videos.add(favorite)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def remove_favorite_video(request, pk):
    if request.method == 'POST':
        favorite = Videos.objects.get(pk=pk)
        user = request.user
        user.favorite_videos.remove(favorite)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class SearchResultsView(generic.ListView):
    model = Videos
    template_name = 'search_results.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        # object_list = Videos.objects.filter(
        #     Q(title__icontains=query) | Q(map_belong__name__icontains=query)
        # )
        object_list = Videos.objects.annotate(search=SearchVector(
            'title', 'map_belong__name')).filter(search=query, admin_permission=True)
        print(query)
        return object_list


class VideoCreate(CreateView):
    model = Videos
    fields = ['title', 'link', 'map_belong',
              'type_video', 'site']


def twitch(request):
    """
    top five twitch live streams - CS
    """
    headers = twitch_auth()

    result = {}
    url = 'https://api.twitch.tv/helix/streams?game_id=32399&first=5'

    response = requests.get(url, headers=headers)
    if response.status_code == 200:  # SUCCESS
        result = response.json()
        result['success'] = True
    else:
        result['success'] = False
        if response.status_code == 404:  # NOT FOUND
            result['message'] = 'No entry found.'
        else:
            result['message'] = 'The Twitch API is not available at the moment.'
    context = {
        # 'links': ['https://www.twitch.tv/'+res['user_name'] for res in result['data']],
        'streams': result['data']
    }
    return render(request, 'twitch.html', context=context)


def twitch_auth():
    """
    function to get twitch token
    """
    # Build paths inside the project like this: BASE_DIR / 'subdir'.
    BASE_DIR = Path(__file__).resolve().parent.parent

    base = environ.Path(__file__) - 2  # two folders back (/a/b/ - 2 = /)
    env = environ.Env()
    # reading .env file  # reading .env file
    environ.Env.read_env(env_file=base('.env'))
    client_id = 'kg7560bqizr6ip9dk1y9lsd0xsw359'
    client_secret = env('TWITCH_CLIENT_SECRET')

    body = {
        'client_id': client_id,
        'client_secret': client_secret,
        "grant_type": 'client_credentials'
    }
    r = requests.post('https://id.twitch.tv/oauth2/token', body)
    keys = r.json()

    headers = {
        'Client-ID': client_id,
        'Authorization': 'Bearer ' + keys['access_token']
    }
    return headers

templates/catalog/links_detail.html
{% extends "base_generic.html" %}
{% block title %}
  | {{ map_link_list_detail }}
{% endblock title %}
{% block content %}
  {% load custom_tags %}
  <div class="d-flex flex-row justify-content-start m-2">
    <h2 class="align-self-center">Map: {{ map_link_list_detail }}</h2>
    <img id="map_logo"
         class="mx-2 align-self-center"
         height="48"
         width="auto"
         src="https://cstube.s3.amazonaws.com/icon_de_{{ map_link_list_detail }}.png"
         alt="logo of {{ map_link_list_detail }}" />
  </div>
  {% regroup map_link_list_detail.links_set.all|dictsortreversed:"type_video" by type_video as grouped_by_category %}
  {% for category in grouped_by_category %}
    <div class="heading_underline d-flex flex-row justify-content-start m-2">
      <h4>{{ category.grouper }}</h4>
      <img class="type_video_icon align-self-center rounded-circle"
           height="32"
           width="auto"
           src="https://cstube.s3.amazonaws.com/{{ category.grouper }}.png"
           alt="{{ category.grouper }}" />
    </div>
    <ul class="detail_list text-capitalize mb-3">
      {% for link in category.list|dictsort:"site" %}
        <li>
          <a href="{{ link.link }}" target="_blank">
            {{ link.title | replace_with_space }} - <span class="link_info_end">{{ link.site }}</span>
          </a>
        </li>
      {% endfor %}
    </ul>
  {% endfor %}
  <!-- <ul class="detail_list text-capitalize">
  <h4>Smoke</h4>
  {% for link in map_link_list_detail.links_set.all|dictsort:"site" %}
    {% if link.type_video == 'Smoke' %}
      <li><a href="{{ link.link }}" target="_blank">{{ link }}/{{link.site}}</a></li>
    {% endif %}
  {% endfor %}

  <h4>Molly</h4>
  {% for link in map_link_list_detail.links_set.all|dictsort:"site" %}
    {% if link.type_video == 'Molly' %}
      <li><a href="{{ link.link }}" target="_blank">{{ link }}/{{link.site}}</a></li>
    {% endif %}
  {% endfor %}
  
  <h4>Flash</h4>
  {% for link in map_link_list_detail.links_set.all|dictsort:"site" %}
    {% if link.type_video == 'Flash' %}
      <li><a href="{{ link.link }}" target="_blank">{{ link }}/{{link.site}}</a></li>
    {% endif %}
  {% endfor %}

  <h4>Grenade</h4>
  {% for link in map_link_list_detail.links_set.all|dictsort:"site" %}
    {% if link.type_video == 'Nade' %}
      <li><a href="{{ link.link }}" target="_blank">{{ link }}/{{link.site}}</a></li>
    {% endif %}
  {% endfor %}

</ul> -->
{% endblock content %}

templates/catalog/links_list.html
{% extends "base_generic.html" %}
<!-- title -->
{% block title %}
  | Maps (csgonades)
{% endblock title %}
{% block content %}
  <h2 class="px-3">Maps (csgonades)</h2>
  <ul class="container-fluid img_link row">
    {% for map in map_link_list %}
      <li class="col-md-4 my-2">
        <div class="inner-map">
          <a href="{% url 'link-detail' pk=map.pk %}">
            <img height="100%"
                 width="100%"
                 src="https://cstube.s3.amazonaws.com/de_{{ map }}.jpg"
                 alt="">
            <p>
              <span id="maps_name">{{ map }}</span> - <span id="maps_number">{{ map.links_set.all.count }}</span>
            </p>
          </a>
        </div>
      </li>
    {% endfor %}
  </ul>
{% endblock content %}

templates/catalog/maps_detail.html
{% extends "base_generic.html" %}
{% block title %}
  | {{ maps }}
{% endblock title %}
{% block content %}
  {% load custom_tags %}
  <div class="d-flex flex-row justify-content-start m-2">
    <h2 class="align-self-center">Map: {{ maps }}</h2>
    <img id="map_logo"
         class="mx-2 align-self-center"
         height="48"
         width="auto"
         src="https://cstube.s3.amazonaws.com/icon_de_{{ maps }}.png"
         alt="logo of {{ maps }}">
  </div>
  <ul class="detail_list text-capitalize">
    {% regroup maps.videos_set.all|dictsortreversed:"type_video" by type_video as grouped_by_category %}
    {% for category in grouped_by_category %}
      <div class="d-flex flex-row justify-content-start m-2 detail_header">
        <h4>{{ category.grouper }}</h4>
        <img class="type_video_icon align-self-center rounded-circle"
             height="32"
             width="auto"
             src="https://cstube.s3.amazonaws.com/{{ category.grouper }}.png"
             alt="{{ category.grouper }}">
      </div>
      <ul class="detail_list text-capitalize mb-5">
        {% for video in category.list|dictsort:"site" %}
          <li class="d-flex flex-row">
            {% comment %} <a href="/catalog/videos/{{ video.pk }}"> {% endcomment %}
            <a href="{% url 'videos-detail' pk=video.pk %}">
              {% if video.admin_permission %}
                {{ video }} - <span class="link_info_end">{{ video.site }}</span>
                {% if video in user.favorite_videos.all %}
                  <i class="bi bi-star-fill link_favorited mx-2 align-self-center"></i>
                {% endif %}
              {% endif %}
            </a>
          </li>
        {% endfor %}
      </ul>
    {% endfor %}
  </ul>
{% endblock content %}

templates/catalog/maps_list.html
{% extends "base_generic.html" %}
<!-- title -->
{% block title %}
  | Maps
{% endblock title %}
{% block content %}
  {% load custom_tags %}
  <h2 class="px-3">Maps</h2>
  <ul class="container-fluid img_link row">
    {% for map in maps_list %}
      <li class="col-md-4 my-2">
        <div class="inner-map">
          <a href="{% url 'map-detail' pk=map.pk %}">
            <img height="100%"
                 width="100%"
                 src="https://cstube.s3.amazonaws.com/de_{{ map }}.jpg"
                 alt="">
            <p>
              <span id="maps_name">{{ map }}</span> - <span id="maps_number">{{ map.videos_set.all | map_filter }}</span>
            </p>
          </a>
        </div>
      </li>
    {% endfor %}
  </ul>
{% endblock content %}

templates/catalog/videos_detail.html
{% extends "base_generic.html" %}
<!-- title -->
{% block title %}
  | {{ videos.title }}
{% endblock title %}
{% block content %}
  <div class="video_player_outer">
    <div class="video_detail_header d-flex align-items-center">
      <h2>Video: {{ videos.title }}</h2>
      {% if user.is_authenticated %}
        {% if videos in user.favorite_videos.all %}
          <form id="favorite_videos{{ videos.id }}"
                method="post"
                action="{% url 'remove-favorite-video' videos.id %}">
            {% csrf_token %}
            <button class="btn btn-danger rounded-circle fs-3 mx-4 shadow"
                    type="submit"
                    data-bs-toggle="tooltip"
                    title="Remove video from favorites">
              <i class="bi bi-folder-minus"></i>
            </button>
          </form>
        {% else %}
          <form id="favorite_videos{{ videos.id }}"
                method="post"
                action="{% url 'add-favorite-video' videos.id %}">
            {% csrf_token %}
            <button class="btn btn-danger rounded-circle fs-3 mx-4 shadow"
                    type="submit"
                    data-bs-toggle="tooltip"
                    title="Add video to favorites">
              <i class="bi bi-folder-plus"></i>
            </button>
          </form>
        {% endif %}
      {% endif %}
    </div>
    <div class="youtube_player video_player">
      <iframe width="100%"
              height="100%"
              src="https://www.youtube.com/embed/{{ videos.youtube_id }}"
              frameborder="0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
              allowfullscreen>
      </iframe>
    </div>
  </div>
{% endblock content %}

templates/catalog/videos_form.html
{% extends "base_generic.html" %}
{% block title %}
  | Add Video
{% endblock title %}
{% block content %}
  <div class="video_add_outer">
    <h2>Add a Video</h2>
    <form action="" method="post" class="video_add">
      {% csrf_token %}
      <table class="video_add_table">
        {{ form.as_table }}
      </table>
      <input type="submit" value="Submit" class="submit_btn">
    </form>
    <p>*Videos require admin permission to be shown.</p>
  </div>
{% endblock content %}

templates/catalog/videos_list.html
{% extends "base_generic.html" %}
<!-- title -->
{% block title %}
  | Videos
{% endblock title %}
{% block content %}
  <form class="search_video m-3"
        action="{% url 'search_results' %}"
        method="get">
    <input name="q" type="text" placeholder="Search...">
    <div class="search"></div>
  </form>
  <h2>Videos</h2>
  <ul class="detail_list text-capitalize">
    {% for video in videos_list|dictsortreversed:"id" %}
      <li class="d-flex flex-row">
        <a href="{% url 'videos-detail' pk=video.pk %}">
          {{ video }} - <span class="map_belong_info">{{ video.map_belong }}</span>
        </a>
        {% if video in user.favorite_videos.all %}
          <i class="bi bi-star-fill link_favorited mx-2 align-self-center"></i>
        {% endif %}
      </li>
    {% endfor %}
  </ul>
{% endblock content %}